version: '3.4'

services:

  minio:
    platform: linux/amd64
    image: quay.io/minio/minio
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MINIO_ROOT_USER: administrador
      MINIO_ROOT_PASSWORD: adminpsswd
      MINIO_PORT_1: 9000
      MINIO_PORT_2: 9090
      MINIO_ENDPOINT: http://minio:9090
    command: [
      "server",
      "/data",
      "--console-address",
      ":9090"
    ]
    ports:
      - ${MINIO_PORT_1}:9000
      - ${MINIO_PORT_2}:9090
    volumes:
      - ../collector/data/:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
